import { sfxFallback } from '../sfx/defaults';
import type { Configs } from './schemas';

export const configFallbacks: Configs = {
  sfx: sfxFallback,
  game: {
    tutorial: {
      nitroArrowMinDistance: 25,
      nitroArrowMaxDistance: 40,
      horseArrowMinTimeToObstacle: 2,
      horseArrowMaxTimeToObstacle: 5,
      horseJumpArrowMinTimeToObstacle: 1.3,
      horseJumpArrowMaxTimeToObstacle: 3,
      slowMoStartTimeToContact: 0.82,
      slowMoPassTimeoutSeconds: 0.5,
      slowMoScale: 0.48,
      slowMoBlendSeconds: 0.25,
      audioMinPlaybackRate: 0.68,
      audioPlaybackRatePower: 0.85,
      audioDetuneCents: -70,
    },
    levelIntro: {
      countdownSeconds: 3,
      moveDelaySeconds: 0.5,
      musicDelaySeconds: 1.5,
      obstacleMinSeconds: 2,
      obstacleMaxSeconds: 4,
      cameraSideX: 2.2,
      cameraSideY: 0.45,
      cameraSideZ: -1.6,
    },
    speeds: {
      base: 10,
      min: 7,
      max: 28,
      rampPerSecond: 0.26,
      accelPerSecond: 1.8,
      decelPerSecond: 0.5,
      speedFloor: 0.8,
    },
    skillMomentum: {
      enabled: true,
      gateNoDamageSeconds: 15,
      speedThresholdRatio: 0.8,
      maxBonus: 0.3,
      rampUpSeconds: 20,
      rampDownSeconds: 15,
      speedEmaSeconds: 4,
    },
    input: {
      bufferMs: 100,
    },
    beatLaunch: {
      windowSeconds: 36,
      strongEnergyThreshold: 0.65,
      speedPerBeat: 0.49,
      maxBonus: 4.42,
    },
    obstaclePanicFlee: {
      durationSeconds: 0.8,
      minStartZ: 22,
      maxStartZ: 85,
      counterflowAlongSpeed: 12.5,
      parallelAlongSpeed: 14,
      lateralSpeed: 10.5,
      lateralRampSeconds: 0.28,
      alongRampSeconds: 0.2,
      yawMaxRadians: 0.62,
      yawRampSeconds: 0.42,
    },
    musicScenes: {
      minArrivalSeconds: 2.4,
      maxArrivalSeconds: 4.0,
      cooldownSeconds: 6.0,
      cueEnergyRiseThreshold: 0.08,
      echoChance: 0.0,
      echoCooldownSeconds: 0.0,
      echoMinRemainingSeconds: 1.2,
      echoEnergyThreshold: 0.25,
      echoMinArrivalSeconds: 0.6,
      echoMaxArrivalSeconds: 1.15,
    },
    lane: {
      positions: [-2.88, -0.96, 0.96, 2.88],
      switchTimeSeconds: 0.15,
    },
    jump: {
      durationSeconds: 0.6,
      height: 1.9,
    },
    horse: {
      flightTimeSeconds: 0.9,
      landingTimeSeconds: 0.1,
      height: 2.3,
      jumpBufferSeconds: 0.18,
      jumpEarlyRestartHeight: 0.55,
      fastFallMultiplier: 4.0,
      momentumPerClear: 0.125,
      maxSpeedBoost: 0.6,
      maxMomentumNitroThreshold: 0.75,
      speedFxStartMomentum: 0.55,
      transitionSpeedCarrySeconds: 1.2,
      modeBonusMinSeconds: 14,
      carBonusMinSeconds: 10,
      carBonusGuaranteedSeconds: 17,
      modeBonusMaxSeconds: 22,
      lateSongSwitchStartProgress: 0.45,
      lateSongSwitchMinSeconds: 8,
      lateSongSwitchMaxSeconds: 11,
      lateSongHorseRampTrainChanceMultiplier: 0.46,
      firstHorseMinSeconds: 30,
      firstHorseGuaranteedSeconds: 40,
      horseRampPickupChance: 0.84,
      horseTrainPickupChance: 0.8,
      roadHorsePickupChance: 0.35,
      lateSongRoadHorsePickupChance: 0.75,
      roadHorsePickupRows: 5,
      roadHorsePickupGapZ: 8,
      carJumpPickupChance: 0.82,
      carJumpPickupMinGroupSize: 3,
      carJumpPickupTargetProgress: 0.88,
      carBonusVisualScale: 3.78,
      horseBonusVisualScale: 3.78,
      horseTrainPickupSpawnLeadSeconds: 2.5,
      horseTrainPickupEncounterRemainingSeconds: 0.4,
      carPortalChance: 0.5,
      carPortalMinLeadSeconds: 1.8,
      carPortalMaxLeadSeconds: 3.2,
      carPortalSafeSeconds: 1.1,
      coinCollectGrace: 0.22,
      cameraYOffset: 0.08,
      rampFallCameraLookBoost: 1.05,
      rampFallCameraYOffset: -0.58,
      rampFallCameraBlendRate: 7,
      rampFallCameraBank: 0,
      airCameraFovBoost: 3,
      airCameraBackOffset: 0.25,
      airCameraYOffset: -0.7,
      airCameraLookBoost: 0.5,
      airCameraBlendRate: 8,
      airCameraFollowSuppression: 0.75,
      slideHeight: 0.36,
      slideClearanceHeight: 0.58,
      slideMinSeconds: 0.32,
      slideExitBufferSeconds: 0.12,
      slideAutoLeadSeconds: 0.7,
      slideCameraYOffset: -1.82,
      slideCameraLookYOffset: -0.48,
      slideCameraBlendRate: 10,
      slideCameraBank: 0.28,
      boostPulseDecayPerSecond: 4.5,
      actionSmashMaxStrength: 3.5,
      actionSmashDelaySeconds: 0.14,
      actionSmashMinMomentum: 0.5,
      blasterMomentumThreshold: 0.75,
      blasterBlastRadius: 18,
      blasterBlastStrength: 5,
      meterSegments: 4,
      overdriveDurationSeconds: 4.0,
      overdriveRecoveryMomentum: 0.75,
      overdriveSpeedBoost: 0.25,
      environmentTransitionSeconds: 2.75,
      landingSquatSeconds: 0.4,
      landingSquatCameraY: -0.26,
      landingSquatLookY: -0.07,
      landingSquatHeadY: -0.14,
      landingSquatRampScale: 1.45,
      landingSquatRampSeconds: 0.48,
    },
    rocket: {
      fuelSeconds: 3.92,
      peakHeight: 8.8,
      plateauSeconds: 0.85,
      speedBoost: 3.0,
      maxSpeed: 52,
      switchTimeSeconds: 0.2,
      launchSeconds: 3,
      anticipationSeconds: 1.5,
      anticipationFovDip: 10,
      anticipationSpeedScale: 0.88,
      anticipationClimbFraction: 0.34,
      turboSnapSeconds: 0.34,
      turboVignettePeakSeconds: 1,
      turboVignettePeak: 0.88,
      turboVignetteSustain: 0.38,
      fallGravity: 18,
      fxFadeSeconds: 0.18,
      returnCarrySeconds: 0.9,
      firstRocketMinSeconds: 30,
      postFirstHorseDelaySeconds: 10,
      spawnCooldownSeconds: 14,
      maxPickupsPerSong: 2,
      minPickupSpacingProgress: 0.22,
      minModeSwitchSeconds: 18,
      guaranteedModeSwitchSeconds: 34,
      rampPickupChance: 0.5,
      jumpPickupChance: 0.42,
      jumpPickupMinGroupSize: 3,
      jumpPickupTargetProgress: 0.58,
      corridorSeconds: 1.4,
      postLandingRampCooldownSeconds: 5,
      coinSpacingSeconds: 0.07,
      coinsPerLaneSegment: 8,
      coinEndBufferSeconds: 0.22,
      pickupPulseSeconds: 0.45,
      bonusVisualScale: 2.4,
      cameraYOffset: 0.82,
      cameraZOffset: 3.15,
      cameraBankAngle: 0.55,
      launchCameraPitchMax: 0.34,
      launchCameraPitchBounce: 1.35,
      launchCameraPlateauBounceSeconds: 0.58,
      launchCameraPullbackZ: 2.8,
      launchCameraLaneBankScale: 0.475,
      launchCameraFovDip: 11,
      cameraBankBlendRate: 5.5,
      cameraFovBoost: 22,
      cameraBlendRate: 3.4,
      launchArcCameraLookLift: 1.35,
      launchArcNosePitch: 0.22,
      launchCameraDipAnticipationY: 0.65,
      launchCameraDipLaunchY: 1.85,
      launchCameraLookAnticipation: -0.52,
      launchCameraLookLaunch: -0.34,
      launchCameraReturnStart: 0.85,
      launchCameraBounceOvershoot: 1.48,
      launchCameraLagToTopStart: 0.16,
      launchCameraLagToTopEnd: 0.62,
      audioMuffleMax: 0.72,
      audioMuffleMinHz: 280,
      audioMuffleAttackSeconds: 0.45,
      audioMuffleReleaseSeconds: 0.06,
      audioTurboShelfGainDb: 7.2,
      audioTurboGainBoost: 0.14,
      audioTurboSnapSeconds: 0.05,
      audioTurboReleaseSeconds: 0.38,
      audioSampleMusicGain: 0.56,
      audioSampleMusicAttackSeconds: 0.55,
      audioSampleMusicReleaseSeconds: 1.5,
      environmentTransitionSeconds: 0.85,
    },
    ramp: {
      startDelaySeconds: 10,
      cooldownSeconds: 10,
      flightTimeSeconds: 3.0,
      landingTimeSeconds: 0.5,
      height: 8.0,
      boostMultiplier: 1.6,
      retainedSpeedDecaySeconds: 6,
      trickCooldownSeconds: 0.3,
      trickNitroGain: 5,
      trickCoinGain: 1,
      trickSeriesStart: 2,
      trickSeriesScoreMultiplier: 1,
      airCoinCalmCount: 8,
      airCoinActiveCount: 12,
      airCoinStartSeconds: 0.45,
      airCoinEndSeconds: 2.55,
      trainLandingEngageStart: 0.4,
      trainLandingLaneSeconds: 0.5,
    },
    train: {
      chance: 0.32,
      cooldownSeconds: 15,
      height: 2.7,
      width: 2.1,
      lengthMultiplier: 0.585,
      landingInset: 6,
      allowedLanes: [1, 2],
      fov: 100,
      exitDurationSeconds: 0.7,
      exitArcHeight: 1.2,
      coinSpacingSeconds: 0.36,
      coinHeight: 0.55,
      landingClearSeconds: 1.2,
      speedBoostMultiplier: 1.35,
      retainedSpeedMultiplier: 1.2,
      retainedSpeedDecaySeconds: 8,
      sideBlastAhead: 4,
      sideBlastBehind: 2,
      companionChance: 0.35,
      companionDelayMinSeconds: 1.5,
      companionDelayMaxSeconds: 2,
      companionDurationJitter: 0.15,
      companionDurationScale: 0.62,
      transferLeadSeconds: 0.5,
      companionObstacleDelaySeconds: 0.25,
      companionCoinCutLeadSeconds: 0.4,
      soloLengthScale: 0.72,
      roofObstacleChance: 0.45,
      roofObstacleLandingClearProgress: 0.22,
      roofObstacleProgressMin: 0.55,
      roofObstacleProgressMax: 0.75,
      parallelScrollScale: 0.38,
      counterflowScrollScale: 1.55,
      parallelRideDrainScale: 1.45,
      durations: {
        calm: 2.8,
        buildUp: 3.5,
        intense: 3.5,
        peak: 4.2,
        cooldown: 2.8,
      },
    },
    camera: {
      fov: 55,
      fovMin: 55,
      fovMax: 110,
      positionY: 3.72,
      positionZ: 10.3125,
      lookY: 1.0,
      positionYFollow: 0.6,
      lookYFollow: 0.6,
      carTurnBankScale: 1.38,
      horseTurnBankScale: 1.25,
      carTurnSpring: 150,
      carTurnDamping: 17,
      carTurnBodyYaw: 0.28,
      carTurnBodyRoll: 0.14,
      turnComboWindowSeconds: 0.35,
      turnMomentumDecaySeconds: 0.8,
      turnJellyScaleMax: 1.55,
      turnBankScaleMax: 1.35,
      turnPullbackZMax: 0.42,
      horsePresentationScale: 0.45,
      horseFpsPresentationScale: 0.25,
      horseFpsPullbackScale: 0.1,
      dodgeDipY: 0.18,
      dodgePullbackZ: 0.35,
      dodgeLateralX: 0.22,
      dodgeMinSpeed: 16,
      dodgeInSeconds: 0.16,
      dodgeHoldSeconds: 0.1,
      dodgeOutSeconds: 0.42,
      dodgePresentationEnabled: false,
      presentationClampX: 0.5,
      presentationClampY: 0.28,
      presentationClampZ: 0.9,
    },
    hit: {
      iframeSeconds: 0.8,
      recoverySeconds: 6.0,
      speedPenalty: 0.1,
      zGrace: 0.3,
      zRearTrimRatio: 0.18,
      heightGrace: 0.25,
    },
    adrenaline: {
      max: 100,
      start: 100,
      passiveDrainPerSecond: 5.5,
      drainRampSeconds: 50,
      drainStartScale: 0.52,
      idleLaneSeconds: 2,
      idleLaneDrainBonus: 1.61,
      rocketDrainMultiplier: 1,
      collisionDamage: 25,
      collisionLowHpThreshold: 28,
      collisionLowHpMultiplier: 1,
      damagedThresholdPercent: 60,
      criticalThresholdPercent: 30,
      criticalNitroGainMultiplier: 1.55,
      gainSmash: 15,
      gainCoin: 1.65,
      gainCoinCarMultiplier: 1.22,
      gainCoinHorseMultiplier: 1.22,
      gainCoinRocketMultiplier: 1.68,
      gainNearMiss: 0,
      gainHorseJumpClear: 8,
      gainHorseSlideClear: 6,
      gainNitroBurst: 0,
      nearMissMaxZ: -0.5,
    },
    combo: {
      threatDistance: 30,
      multiplierStep: 5,
      multiplierPerStep: 1,
      chainWindowSeconds: 0.85,
    },
    pulse: {
      decayPerSecond: 4.0,
      strongBeatEnergyThreshold: 0.65,
      channels: {
        background: 0.18,
        ambient: 0.45,
        objectsEmissive: 0.65,
        objectsScale: 0.34,
        coinsScale: 0.5,
        dashesEmissive: 1.0,
      },
    },
    turbo: {
      energyThreshold: 0.35,
      relativeRiseThreshold: 0.1,
      historySeconds: 8.0,
      percentile: 0.8,
      beatSyncTimeoutSeconds: 0.75,
      sustainSeconds: 0.5,
      durationSeconds: 4.0,
      cooldownSeconds: 10.0,
      speedBoost: 1.35,
      entrySeconds: 0.55,
      exitSeconds: 0.7,
      sceneLeadSeconds: 1.45,
      sceneRows: 3,
      earlyTrackSeconds: 45,
      earlyTrackBeatSyncSeconds: 0.15,
      earlyTrackEntrySeconds: 0.15,
    },
    nitro: {
      maxFill: 100,
      gainPerCoin: 4.35,
      gainPerDodge: 8,
      gainPerChargeLaneSecond: 2.5,
      drainPerSecond: 32.5,
      graceSeconds: 0.1,
      boostMax: 0.6,
      coinNitroMultiplier: 2,
      gainPerSmash: 3,
      gainPerNearMiss: 1,
      scoreMultiplier: 2,
      camYOffset: -0.8,
      smashGraceSeconds: 0.25,
      readyCollisionBlastRadius: 16,
      readyCollisionBlastStrength: 4.5,
      warningSeconds: 0.5,
      audioClearSeconds: 1.5,
      audioShelfGainDb: 3.1,
      audioShelfFrequencyHz: 1850,
      audioGainBoost: 0.052,
      salvation: {
        minChargePercent: 60,
        baseChance: 0.16,
        lateProgressStart: 0.35,
        lateProgressBonus: 0.40,
        lookaheadRows: 10,
        minMultiLaneRows: 2,
        minTallAhead: 2,
        flashSeconds: 0.55,
        smashStrengthMultiplier: 2.8,
      },
    },
    postfx: {
      blurMax: 0,
      blurInner: 0.65,
      blurOuter: 1.0,
      samples: 8,
      blurSpread: 0.22,
      kickStrength: 0.27,
      shakeSpeed: 0.045,
      vigStrength: 0.3,
      vigInner: 0.45,
      windMinSpeed: 0.4,
      windFadeRange: 8.0,
      windCount: 8,
      lineMaxLength: 4.0,
      lineMaxAlpha: 0.5,
      bankStrength: 0.04,
      shakeNitroBoost: 3,
      bankNitroBoost: 2.5,
      shakeSkillMomentumBoost: 0.85,
      greenSmashFovBoost: 0.12,
    },
    player: {
      width: 0.9,
      height: 0.9,
      depth: 0.9,
    },
    obstacle: {
      width: 2.0,
      depth: 1.5,
      lowWidth: 1.2,
      lowDepth: 2.32,
      tallWidth: 1.5,
      tallDepth: 5.1,
      tallHeight: 2.05,
      lowHeight: 1.1,
      microHeight: 0.72,
      microWidthScale: 0.34,
      microDepthScale: 0.38,
    },
    destroy: {
      gainPerMicroBreak: 7,
      gainPerMediumSmash: 6,
      gainPerDodge: 3.2,
      softHitSpeedPenalty: 0.08,
      softHitPenaltySeconds: 0.45,
      mediumHitSpeedPenalty: 0.15,
      mediumHitPenaltySeconds: 0.62,
      tallHitSpeedPenalty: 0.1,
      microClusterProbability: 0.48,
      microClusterSizeMin: 2,
      microClusterSizeMax: 3,
      microRowChance: 0.34,
      mediumDensityScale: 1.05,
      microChunkWeight: 0.22,
      obstacleChunkWeightBoost: 0.08,
      nitroTrafficMinLeadSeconds: 3.4,
      nitroTallProbabilityScale: 1.82,
      nitroMicroSpawnScale: 0.42,
      nitroMediumSpawnScale: 0.32,
      nitroSmashRowChance: 0.2,
      nitroMaxMediumPerLaneRows: 1,
      nitroLateStartProgress: 0.24,
      nitroLateChargeGainScale: 0.45,
      nitroLateChallengeScale: 0.24,
      nitroLateMicroSpawnScale: 0.44,
      nitroLateMediumSpawnScale: 0.52,
      laneCommitmentMaxSeconds: 3.2,
      laneCommitmentNitroMaxSeconds: 2.35,
      damageAudioMaxWet: 0.58,
      damageAudioMinHz: 900,
      damageAudioMaxGainReduction: 0.24,
      damageAudioAttackSeconds: 0.2,
      damageAudioReleaseSeconds: 0.035,
      damageAudioDamagedStress: 0.58,
      mediumKnockbackLateralSpeed: 6.6,
      mediumKnockbackArcUpSpeed: 3.5,
      mediumKnockbackGravity: 19,
      mediumKnockbackBackwardSpeed: -1.6,
      mediumKnockbackGreenLateralSpeed: 10.8,
      mediumKnockbackGreenArcUpSpeed: 7.8,
      mediumKnockbackGreenGravity: 15,
      mediumKnockbackGreenForwardSpeed: -3.6,
      mediumKnockbackYellowSpin: 4.8,
      mediumKnockbackGreenSpin: 8.6,
      mediumKnockbackGreenExplodeStrength: 2.4,
      mediumKnockbackDurationSeconds: 1.05,
      mediumKnockbackHitRadius: 1.35,
      greenSmashSpeedBonus: 0.058,
      greenSmashSpeedDecaySeconds: 0.55,
      earlyGreenSmashSpeedScale: 2.3,
      earlyGreenSmashFullSeconds: 14,
      earlyGreenSmashFadeSeconds: 10,
    },
    coin: {
      radius: 0.35,
      value: 10,
      collectGrace: 0.12,
    },
  },
  director: {
    scoring: {
      wEnergy: 1.2,
      wStress: 0.45,
      wPhaseElapsed: 0.3,
      wBrightness: 0.4,
      cooldownPenalty: 0.5,
    },
    music: {
      speedEnergyInfluence: 1.0,
      vfxEnergyInfluence: 1.0,
      speedFloor: 1.0,
      sectionEnergy: {
        attackSeconds: 0.25,
        releaseSeconds: 1.2,
      },
    },
    phases: {
      calm: {
        minDurationSeconds: 2,
        cooldownAfterExitSeconds: 2,
        center: 0.15,
        intents: [
          { target: 'speed', value: 1.0, priority: 0, tag: 'phase:calm' },
          { target: 'obstacleDensity', value: 0.15, priority: 0, tag: 'phase:calm' },
          { target: 'vfxIntensity', value: 0.12, priority: 0, tag: 'phase:calm' },
          { target: 'coinFrequency', value: 0.75, priority: 0, tag: 'phase:calm' },
        ],
      },
      buildUp: {
        minDurationSeconds: 2,
        cooldownAfterExitSeconds: 2,
        center: 0.45,
        intents: [
          { target: 'speed', value: 1.0, priority: 0, tag: 'phase:buildUp' },
          { target: 'obstacleDensity', value: 0.5, priority: 0, tag: 'phase:buildUp' },
          { target: 'vfxIntensity', value: 0.5, priority: 0, tag: 'phase:buildUp' },
          { target: 'coinFrequency', value: 0.65, priority: 0, tag: 'phase:buildUp' },
        ],
      },
      intense: {
        minDurationSeconds: 2,
        cooldownAfterExitSeconds: 3,
        center: 0.7,
        intents: [
          { target: 'speed', value: 1.18, priority: 0, tag: 'phase:intense' },
          { target: 'obstacleDensity', value: 0.75, priority: 0, tag: 'phase:intense' },
          { target: 'vfxIntensity', value: 0.78, priority: 0, tag: 'phase:intense' },
          { target: 'coinFrequency', value: 0.45, priority: 0, tag: 'phase:intense' },
        ],
      },
      peak: {
        minDurationSeconds: 2,
        cooldownAfterExitSeconds: 6,
        center: 0.9,
        intents: [
          { target: 'speed', value: 1.32, priority: 0, tag: 'phase:peak' },
          { target: 'obstacleDensity', value: 1.0, priority: 0, tag: 'phase:peak' },
          { target: 'vfxIntensity', value: 1.0, priority: 0, tag: 'phase:peak' },
          { target: 'coinFrequency', value: 0.65, priority: 0, tag: 'phase:peak' },
        ],
      },
      cooldown: {
        minDurationSeconds: 2,
        cooldownAfterExitSeconds: 1,
        center: 0.2,
        intents: [
          { target: 'speed', value: 1.0, priority: 0, tag: 'phase:cooldown' },
          { target: 'obstacleDensity', value: 0.2, priority: 0, tag: 'phase:cooldown' },
          { target: 'vfxIntensity', value: 0.15, priority: 0, tag: 'phase:cooldown' },
          { target: 'coinFrequency', value: 0.8, priority: 0, tag: 'phase:cooldown' },
        ],
      },
    },
    constraints: {
      maxSpeedDeltaPerSecond: 4,
      minSecondsBetweenMajorEvents: 6,
      minSecondsBetweenCameraChanges: 5,
      hysteresisUp: 0.1,
      hysteresisDown: 0.18,
    },
    defaultIntents: [
      { target: 'speed', value: 1.0, priority: 0, tag: 'phase:calm' },
      { target: 'obstacleDensity', value: 0.4, priority: 0, tag: 'phase:calm' },
    ],
  },
  levelgen: {
    chunkLength: 30,
    contentStartZ: 12,
    segmentsAhead: 3,
    segmentsBehind: 2,
    lanes: 4,
    minGapZ: 4,
    segmentWeights: {
      obstacle: 0.59,
      coins: 0.3,
      bonus: 0.1,
      empty: 0.01,
    },
    densityRange: [0.28, 0.86],
    baseDensity: 0.36,
    musicDensityDeltaMax: 0.1,
    coinHeight: 0.6,
    coinRoutes: {
      obstacleGuideProbability: 0.58,
      riskChoiceProbability: 0.28,
    },
    fairness: {
      referenceSpeed: 28,
      speedSampleStep: 2,
      laneSwitchSeconds: 0.15,
      minDecisionSeconds: 0.28,
      obstaclePaddingSeconds: 0.08,
      routeGuideShare: 0.72,
      mandatoryRampGuideClusters: 2,
      freeRampGuideClusters: 1,
      microLeadMinGapZScale: 1.75,
    },
    carHazardSpacing: {
      tallTallMinGapScale: 1.65,
      mixedMinGapScale: 1.35,
      lowLowMinGapScale: 1,
      compactTallChains: false,
    },
    bonusLeadZ: 100,
    bonusMinGapZ: 60,
    seedBehavior: 'session',
    wallProbability: 0.07,
    wallProbabilityNoNitro: 0.022,
    wallCooldownSeconds: 8,
    nitroWallProbability: 0.38,
    nitroActiveFullRowProbability: 0.4,
    nitroReadyChallengeProbability: 0.13,
    nitroReadyMandatoryProbability: 0.12,
    nitroChallengeCooldownRows: 6,
    tallProbability: 0.36,
    earlyTallBias: 0.10,
    trackEndObstacleStopSeconds: 5,
    twoObstacleBias: 0.5,
    shoulderPasserProbability: 0.058,
    shoulderPasserSpeedMultiplier: 3.05,
    minWallGapRows: 3,
    laneFlow: [0, -6, 17, 0],
    multiLaneFlowFactor: 0.25,
    counterflowPassabilityLingerSeconds: 1.85,
    counterflowSpawnLagScale: 0.32,
    nitroChargeLanes: [1, 2],
    nitroCoinFrequencyMultiplier: 0.35,
    rampProbability: 0.025,
    earlyRampProbability: 0,
    earlyRampRows: 0,
    rampMinGapRows: 3,
    redWallProbability: 0.18,
    rampLeadRows: 3,
    longRunDifficulty: {
      delaySeconds: 17,
      rampSeconds: 150,
      maxDensityBonus: 0.052,
      maxMultiObstacleBiasBonus: 0.026,
      lateSongEaseStartProgress: 0.78,
      lateSongEaseMaxReduction: 0.055,
    },
    earlyTraffic: {
      rows: 30,
      densityBonus: 0.09,
      laneWeight: 1.9,
      lanes: [1, 2],
      forcedObstacleRows: 14,
      maxOpeningEmptyGapZ: 16,
    },
    riskZone: {
      riskLanes: [2],
      obstacleWeight: 1.6,
      coinWeight: 2.4,
    },
    car: {
      phasesEnabled: false,
      phaseMinChunks: 2,
      phaseMaxChunks: 4,
      phaseWeights: {
        stream: 0.25,
        weave: 0.35,
        breather: 0.22,
        nitroTease: 0.18,
      },
      waveMinChunks: 4,
      waveMaxChunks: 7,
      waveIntensityPeak: 0.75,
      longRunWeaveWeightBonus: 0.12,
      longRunNitroTeaseWeightBonus: 0.1,
      longRunBreatherWeightPenalty: 0.08,
      streamLaneStickiness: 0.72,
      streamDensityScale: 1,
      weaveDensityScale: 1,
      weaveMultiObstacleBiasBonus: 0,
      breatherDensityScale: 1,
      breatherObstacleWeightScale: 1,
      nitroTeaseDensityScale: 1,
      nitroTeaseReadyChallengeMultiplier: 1,
      nitroTeaseCoinFrequencyMultiplier: 1,
    },
    horse: {
      actionChunkProbability: 0.84,
      slideGroupProbability: 0.25,
      mandatoryActionProbability: 0.65,
      jumpGroupMin: 1,
      jumpGroupMax: 3,
      slideGroupMin: 3,
      slideGroupMax: 5,
      longSlideGroupProbability: 0.14,
      longSlideGroupMin: 6,
      longSlideGroupMax: 8,
      slideSpacingZ: 3,
      jumpFollowupProbability: 0.48,
      jumpFollowupSlideProbability: 0.55,
      slideStartChunks: 1,
      restChunkProbability: 0.05,
      slideToJumpMinGapZ: 24,
      highSpeedEaseStartMomentum: 0.7,
      highSpeedActionMultiplier: 0.82,
      highSpeedMandatoryMultiplier: 0.78,
      highSpeedFollowupMultiplier: 0.7,
      jumpCoinGroupProbability: 0.92,
      jumpCoinHeight: 2.05,
      groundCoinProbability: 0.3,
      restCoinStride: 2,
      coinMaxSameLaneStreak: 3,
      coinWeaveStride: 2,
      dodgeOnlyProbability: 0.34,
      dodgeOnlyMaxGapChunks: 3,
      dodgeBlockedMin: 2,
      dodgeBlockedMax: 3,
      maxSameActionStreak: 2,
      slideFollowupDodgeProbability: 0.4,
      convertibleShoulderPunishGapZ: 10,
      slideCoinProbability: 0.86,
      phasesEnabled: false,
      phaseMinChunks: 2,
      phaseMaxChunks: 4,
      phaseWeights: {
        corridor: 0.25,
        weave: 0.35,
        breather: 0.22,
        overdriveTease: 0.18,
      },
      waveMinChunks: 4,
      waveMaxChunks: 7,
      waveIntensityPeak: 0.75,
      longRunWeaveWeightBonus: 0.12,
      longRunOverdriveTeaseWeightBonus: 0.1,
      longRunBreatherWeightPenalty: 0.08,
      corridorActionScale: 1,
      corridorDodgeProbabilityScale: 1,
      corridorDodgeLaneStickiness: 0,
      weaveActionScale: 1,
      weaveSlideProbabilityBonus: 0,
      weaveFollowupScale: 1,
      weaveGroupSizeBonus: 0,
      breatherActionScale: 1,
      breatherRestChunkScale: 1,
      breatherGroundCoinScale: 1,
      overdriveTeaseActionScale: 1,
      overdriveTeaseMandatoryScale: 1,
      overdriveTeaseFollowupScale: 1,
      overdriveTeaseJumpCoinBonus: 0,
      overdriveTeaseGroupSizeBonus: 0,
      frontierTownProbability: 0.12,
      frontierTownIntroChunks: 3,
      frontierTownMinChunks: 3,
      frontierTownMaxChunks: 4,
      frontierTownCooldownChunks: 6,
    },
  },
  audio: {
    latencyOffsetMs: 40,
    fftSize: 512,
    blockSamples: 128,
    energy: {
      attackSeconds: 0.05,
      releaseSeconds: 0.3,
      minRiseSeconds: 5,
      maxFallSeconds: 10,
    },
    brightness: {
      attackSeconds: 0.1,
      releaseSeconds: 0.5,
      minRiseSeconds: 5,
      maxFallSeconds: 10,
    },
    beat: {
      thresholdK: 1.8,
      minIntervalMs: 150,
      rollingWindow: 43,
    },
    silence: {
      rmsThreshold: 0.02,
      minFrames: 20,
      debounceMs: 500,
      exitFactor: 2,
    },
    trackEndFadeSeconds: 10,
  },
  debug: {
    prototypeMode: false,
    recording: {
      enabled: false,
      autoExport: false,
    },
    timeline: {
      zoomSecondsPerScreen: 15,
    },
    overlay: {
      showFps: true,
      showStates: true,
      showIntents: true,
    },
  },
};
