import { sfxConfigSchema, type SfxConfig } from '../sfx/config';
import { z } from 'zod';
import { MUSIC_PLANNING_DEFAULTS } from '../gameplay/musicPlanning';

export const gameConfigSchema = z.object({
  tutorial: z.object({
    nitroArrowMinDistance: z.number().nonnegative(),
    nitroArrowMaxDistance: z.number().positive(),
    horseArrowMinTimeToObstacle: z.number().positive(),
    horseArrowMaxTimeToObstacle: z.number().positive(),
    horseJumpArrowMinTimeToObstacle: z.number().positive(),
    horseJumpArrowMaxTimeToObstacle: z.number().positive(),
    slowMoStartTimeToContact: z.number().positive(),
    slowMoPassTimeoutSeconds: z.number().positive(),
    slowMoScale: z.number().min(0.01).max(1),
    slowMoBlendSeconds: z.number().positive(),
    audioMinPlaybackRate: z.number().min(0.25).max(1),
    audioPlaybackRatePower: z.number().positive(),
    audioDetuneCents: z.number().min(-1200).max(1200),
  }).refine((value) => value.nitroArrowMaxDistance >= value.nitroArrowMinDistance, {
    message: 'tutorial nitro max distance must be >= min distance',
  }).refine((value) => value.horseArrowMaxTimeToObstacle >= value.horseArrowMinTimeToObstacle, {
    message: 'tutorial horse max time must be >= min time',
  }).refine((value) => value.horseJumpArrowMaxTimeToObstacle >= value.horseJumpArrowMinTimeToObstacle, {
    message: 'tutorial horse jump max time must be >= min time',
  }).refine((value) => value.slowMoStartTimeToContact < value.horseJumpArrowMinTimeToObstacle, {
    message: 'tutorial slow-mo must start after horse jump target acquisition',
  }).refine((value) => value.slowMoStartTimeToContact < value.horseArrowMinTimeToObstacle, {
    message: 'tutorial slow-mo must start after horse target acquisition',
  }),
  levelIntro: z.object({
    countdownSeconds: z.number().positive(),
    moveDelaySeconds: z.number().nonnegative(),
    musicDelaySeconds: z.number().nonnegative(),
    obstacleMinSeconds: z.number().positive(),
    obstacleMaxSeconds: z.number().positive(),
    cameraSideX: z.number(),
    cameraSideY: z.number(),
    cameraSideZ: z.number(),
  }).refine((value) => value.countdownSeconds > value.moveDelaySeconds, {
    message: 'levelIntro countdown must exceed move delay',
  }).refine((value) => value.obstacleMaxSeconds >= value.obstacleMinSeconds, {
    message: 'levelIntro obstacle max must be >= min',
  }),
  speeds: z.object({
    base: z.number().positive(),
    min: z.number().positive(),
    max: z.number().positive(),
    rampPerSecond: z.number().nonnegative(),
    accelPerSecond: z.number().positive(),
    decelPerSecond: z.number().positive(),
    speedFloor: z.number().min(0).max(1),
  }),
  skillMomentum: z.object({
    enabled: z.boolean(),
    gateNoDamageSeconds: z.number().nonnegative(),
    speedThresholdRatio: z.number().min(0.5).max(1),
    maxBonus: z.number().min(0).max(0.5),
    rampUpSeconds: z.number().positive(),
    rampDownSeconds: z.number().positive(),
    speedEmaSeconds: z.number().positive(),
  }),
  input: z.object({
    bufferMs: z.number().int().nonnegative(),
  }),
  beatLaunch: z.object({
    windowSeconds: z.number().nonnegative(),
    strongEnergyThreshold: z.number().min(0).max(1),
    speedPerBeat: z.number().nonnegative(),
    maxBonus: z.number().nonnegative(),
  }),
  obstaclePanicFlee: z.object({
    durationSeconds: z.number().positive(),
    minStartZ: z.number().nonnegative(),
    maxStartZ: z.number().positive(),
    counterflowAlongSpeed: z.number().positive(),
    parallelAlongSpeed: z.number().positive(),
    lateralSpeed: z.number().positive(),
    lateralRampSeconds: z.number().positive(),
    alongRampSeconds: z.number().positive(),
    yawMaxRadians: z.number().positive(),
    yawRampSeconds: z.number().positive(),
  }),
  musicPlanning: z.object({
    enabled: z.boolean(), preparationSeconds: z.number().min(1).max(15),
    lookaheadSeconds: z.number().min(8).max(60), maxFileMB: z.number().min(1).max(256),
    maxDecodedSeconds: z.number().min(20).max(1800), minLeadSeconds: z.number().min(1),
    maxLeadSeconds: z.number().min(1), confidenceThreshold: z.number().min(0).max(1),
    hitWindowMs: z.number().positive(), fallbackBpm: z.number().min(60).max(180),
    introSeconds: z.number().min(15).max(25),
    stageEnds: z.array(z.number().min(0).max(1)).length(3),
    densityCaps: z.array(z.number().min(0).max(1)).length(5),
    actionCaps: z.array(z.number().int().min(1).max(8)).length(5),
    blockedLaneCaps: z.array(z.number().int().min(1).max(3)).length(5),
    reactionSeconds: z.array(z.number().min(0.28).max(2)).length(5),
    speedCaps: z.array(z.number().min(1).max(1.8)).length(5),
  }).refine(value => value.maxLeadSeconds >= value.minLeadSeconds && value.lookaheadSeconds > value.maxLeadSeconds,
    { message: 'music planning horizon must exceed the scheduling lead' }).refine(value => value.stageEnds.every((end, i) => i === 0 || end > value.stageEnds[i - 1]), { message: 'music stages must be ordered' }).default(MUSIC_PLANNING_DEFAULTS),
  musicScenes: z.object({
    minArrivalSeconds: z.number().positive(),
    maxArrivalSeconds: z.number().positive(),
    cooldownSeconds: z.number().nonnegative(),
    cueEnergyRiseThreshold: z.number().nonnegative(),
    echoChance: z.number().min(0).max(1),
    echoCooldownSeconds: z.number().nonnegative(),
    echoMinRemainingSeconds: z.number().positive(),
    echoEnergyThreshold: z.number().min(0).max(1),
    echoMinArrivalSeconds: z.number().positive(),
    echoMaxArrivalSeconds: z.number().positive(),
  }).refine((value) => value.maxArrivalSeconds >= value.minArrivalSeconds, {
    message: 'maxArrivalSeconds must be at least minArrivalSeconds',
  }).refine((value) => value.echoMaxArrivalSeconds >= value.echoMinArrivalSeconds, {
    message: 'echoMaxArrivalSeconds must be at least echoMinArrivalSeconds',
  }),
  lane: z.object({
    positions: z.array(z.number()).length(4),
    switchTimeSeconds: z.number().positive(),
  }),
  jump: z.object({
    durationSeconds: z.number().positive(),
    height: z.number().positive(),
  }),
  horse: z.object({
    flightTimeSeconds: z.number().positive(),
    landingTimeSeconds: z.number().nonnegative(),
    height: z.number().positive(),
    jumpBufferSeconds: z.number().nonnegative(),
    jumpEarlyRestartHeight: z.number().nonnegative(),
    fastFallMultiplier: z.number().min(1),
    momentumPerClear: z.number().positive().max(1),
    maxSpeedBoost: z.number().nonnegative(),
    maxMomentumNitroThreshold: z.number().min(0).max(1),
    speedFxStartMomentum: z.number().min(0).max(1),
    transitionSpeedCarrySeconds: z.number().positive(),
    modeBonusMinSeconds: z.number().nonnegative(),
    carBonusMinSeconds: z.number().nonnegative(),
    carBonusGuaranteedSeconds: z.number().positive(),
    modeBonusMaxSeconds: z.number().positive(),
    lateSongSwitchStartProgress: z.number().min(0).max(1),
    lateSongSwitchMinSeconds: z.number().nonnegative(),
    lateSongSwitchMaxSeconds: z.number().positive(),
    lateSongHorseRampTrainChanceMultiplier: z.number().min(0).max(1),
    firstHorseMinSeconds: z.number().nonnegative(),
    firstHorseGuaranteedSeconds: z.number().nonnegative(),
    horseRampPickupChance: z.number().min(0).max(1),
    horseTrainPickupChance: z.number().min(0).max(1),
    roadHorsePickupChance: z.number().min(0).max(1),
    lateSongRoadHorsePickupChance: z.number().min(0).max(1),
    roadHorsePickupRows: z.number().int().positive(),
    roadHorsePickupGapZ: z.number().positive(),
    carJumpPickupChance: z.number().min(0).max(1),
    carJumpPickupMinGroupSize: z.number().int().positive(),
    carJumpPickupTargetProgress: z.number().min(0).max(1),
    carBonusVisualScale: z.number().positive(),
    horseBonusVisualScale: z.number().positive(),
    horseTrainPickupSpawnLeadSeconds: z.number().positive(),
    horseTrainPickupEncounterRemainingSeconds: z.number().nonnegative(),
    carPortalChance: z.number().min(0).max(1),
    carPortalMinLeadSeconds: z.number().positive(),
    carPortalMaxLeadSeconds: z.number().positive(),
    carPortalSafeSeconds: z.number().nonnegative(),
    coinCollectGrace: z.number().nonnegative(),
    cameraYOffset: z.number(),
    rampFallCameraLookBoost: z.number(),
    rampFallCameraYOffset: z.number(),
    rampFallCameraBlendRate: z.number().positive(),
    rampFallCameraBank: z.number(),
    airCameraFovBoost: z.number().nonnegative(),
    airCameraBackOffset: z.number().nonnegative(),
    airCameraYOffset: z.number(),
    airCameraLookBoost: z.number(),
    airCameraBlendRate: z.number().positive(),
    airCameraFollowSuppression: z.number().min(0).max(1),
    slideHeight: z.number().positive(),
    slideClearanceHeight: z.number().positive(),
    slideMinSeconds: z.number().nonnegative(),
    slideExitBufferSeconds: z.number().nonnegative(),
    slideAutoLeadSeconds: z.number().nonnegative(),
    slideCameraYOffset: z.number(),
    slideCameraLookYOffset: z.number(),
    slideCameraBlendRate: z.number().positive(),
    slideCameraBank: z.number().nonnegative(),
    boostPulseDecayPerSecond: z.number().positive(),
    actionSmashMaxStrength: z.number().min(1),
    actionSmashDelaySeconds: z.number().nonnegative(),
    actionSmashMinMomentum: z.number().min(0).max(1),
    blasterMomentumThreshold: z.number().min(0).max(1),
    blasterBlastRadius: z.number().positive(),
    blasterBlastStrength: z.number().min(1),
    meterSegments: z.number().int().min(2).max(8),
    overdriveDurationSeconds: z.number().positive(),
    overdriveRecoveryMomentum: z.number().min(0).max(1),
    overdriveSpeedBoost: z.number().nonnegative(),
    environmentTransitionSeconds: z.number().positive(),
    landingSquatSeconds: z.number().positive(),
    landingSquatCameraY: z.number(),
    landingSquatLookY: z.number(),
    landingSquatHeadY: z.number(),
    landingSquatRampScale: z.number().positive(),
    landingSquatRampSeconds: z.number().positive(),
  }).refine((value) => value.carPortalMaxLeadSeconds >= value.carPortalMinLeadSeconds, {
    message: 'carPortalMaxLeadSeconds must be at least carPortalMinLeadSeconds',
  }),
  rocket: z.object({
    fuelSeconds: z.number().positive(),
    peakHeight: z.number().positive(),
    plateauSeconds: z.number().nonnegative(),
    speedBoost: z.number().min(1),
    maxSpeed: z.number().positive(),
    switchTimeSeconds: z.number().positive(),
    launchSeconds: z.number().positive(),
    anticipationSeconds: z.number().nonnegative(),
    anticipationFovDip: z.number().nonnegative(),
    anticipationSpeedScale: z.number().min(0.5).max(1),
    anticipationClimbFraction: z.number().min(0).max(1),
    turboSnapSeconds: z.number().positive(),
    turboVignettePeakSeconds: z.number().positive(),
    turboVignettePeak: z.number().min(0).max(1),
    turboVignetteSustain: z.number().min(0).max(1),
    fallGravity: z.number().positive(),
    fxFadeSeconds: z.number().positive(),
    returnCarrySeconds: z.number().positive(),
    firstRocketMinSeconds: z.number().nonnegative(),
    postFirstHorseDelaySeconds: z.number().nonnegative(),
    spawnCooldownSeconds: z.number().nonnegative(),
    maxPickupsPerSong: z.number().int().positive(),
    minPickupSpacingProgress: z.number().min(0).max(1),
    minModeSwitchSeconds: z.number().nonnegative(),
    guaranteedModeSwitchSeconds: z.number().nonnegative(),
    rampPickupChance: z.number().min(0).max(1),
    jumpPickupChance: z.number().min(0).max(1),
    jumpPickupMinGroupSize: z.number().int().positive(),
    jumpPickupTargetProgress: z.number().min(0).max(1),
    corridorSeconds: z.number().positive(),
    postLandingRampCooldownSeconds: z.number().nonnegative(),
    landingAdjustMaxSeconds: z.number().nonnegative(),
    landingSafeSeconds: z.number().nonnegative(),
    coinSpacingSeconds: z.number().positive(),
    coinsPerLaneSegment: z.number().int().positive(),
    coinEndBufferSeconds: z.number().nonnegative(),
    pickupPulseSeconds: z.number().positive(),
    bonusVisualScale: z.number().positive(),
    cameraYOffset: z.number(),
    cameraZOffset: z.number(),
    cameraBankAngle: z.number().nonnegative(),
    launchCameraPitchMax: z.number().nonnegative(),
    launchCameraPitchBounce: z.number().nonnegative(),
    launchCameraPlateauBounceSeconds: z.number().positive(),
    launchCameraPullbackZ: z.number().nonnegative(),
    launchCameraLaneBankScale: z.number().nonnegative(),
    launchCameraFovDip: z.number().nonnegative(),
    cameraBankBlendRate: z.number().positive(),
    cameraFovBoost: z.number().nonnegative(),
    cameraBlendRate: z.number().positive(),
    launchArcCameraLookLift: z.number().nonnegative(),
    launchArcNosePitch: z.number().min(0).max(Math.PI / 2),
    launchCameraDipAnticipationY: z.number().nonnegative(),
    launchCameraDipLaunchY: z.number().nonnegative(),
    launchCameraLookAnticipation: z.number(),
    launchCameraLookLaunch: z.number(),
    launchCameraReturnStart: z.number().min(0).max(1),
    launchCameraBounceOvershoot: z.number().positive(),
    launchCameraLagToTopStart: z.number().min(0).max(1),
    launchCameraLagToTopEnd: z.number().min(0).max(1),
    audioMuffleMax: z.number().min(0).max(1),
    audioMuffleMinHz: z.number().positive(),
    audioMuffleAttackSeconds: z.number().positive(),
    audioMuffleReleaseSeconds: z.number().positive(),
    audioTurboShelfGainDb: z.number().nonnegative(),
    audioTurboGainBoost: z.number().nonnegative(),
    audioTurboSnapSeconds: z.number().positive(),
    audioTurboReleaseSeconds: z.number().positive(),
    audioSampleMusicGain: z.number().min(0).max(1),
    audioSampleMusicAttackSeconds: z.number().positive(),
    audioSampleMusicReleaseSeconds: z.number().positive(),
    environmentTransitionSeconds: z.number().positive(),
  }).refine((value) => value.minModeSwitchSeconds <= value.guaranteedModeSwitchSeconds, {
    message: 'rocket minModeSwitchSeconds must be <= guaranteedModeSwitchSeconds',
  }),
  ramp: z.object({
    startDelaySeconds: z.number().nonnegative(),
    cooldownSeconds: z.number().nonnegative(),
    flightTimeSeconds: z.number().positive(),
    landingTimeSeconds: z.number().nonnegative(),
    height: z.number().positive(),
    boostMultiplier: z.number().min(1),
    retainedSpeedDecaySeconds: z.number().positive(),
    trickCooldownSeconds: z.number().positive(),
    trickNitroGain: z.number().nonnegative(),
    trickCoinGain: z.number().nonnegative(),
    trickSeriesStart: z.number().int().positive(),
    trickSeriesScoreMultiplier: z.number().min(1),
    airCoinCalmCount: z.number().int().positive(),
    airCoinActiveCount: z.number().int().positive(),
    airCoinStartSeconds: z.number().nonnegative(),
    airCoinEndSeconds: z.number().positive(),
    trainLandingEngageStart: z.number().min(0).max(1),
    trainLandingLaneSeconds: z.number().positive(),
  }),
  train: z.object({
    chance: z.number().min(0).max(1),
    cooldownSeconds: z.number().nonnegative(),
    height: z.number().positive(),
    width: z.number().positive(),
    lengthMultiplier: z.number().positive().max(1),
    landingInset: z.number().nonnegative(),
    allowedLanes: z.array(z.number().int().nonnegative()).min(1),
    fov: z.number().min(1).max(170),
    exitDurationSeconds: z.number().positive(),
    exitArcHeight: z.number().nonnegative(),
    coinSpacingSeconds: z.number().positive(),
    coinHeight: z.number().nonnegative(),
    landingClearSeconds: z.number().nonnegative(),
    speedBoostMultiplier: z.number().min(1),
    retainedSpeedMultiplier: z.number().min(1),
    retainedSpeedDecaySeconds: z.number().positive(),
    sideBlastAhead: z.number().nonnegative(),
    sideBlastBehind: z.number().nonnegative(),
    companionChance: z.number().min(0).max(1),
    companionDelayMinSeconds: z.number().nonnegative(),
    companionDelayMaxSeconds: z.number().nonnegative(),
    companionDurationJitter: z.number().min(0).max(1),
    companionDurationScale: z.number().min(0.2).max(1),
    transferLeadSeconds: z.number().nonnegative(),
    companionObstacleDelaySeconds: z.number().nonnegative(),
    companionCoinCutLeadSeconds: z.number().nonnegative(),
    soloLengthScale: z.number().min(0.35).max(1),
    roofObstacleChance: z.number().min(0).max(1),
    roofObstacleLandingClearProgress: z.number().min(0).max(1),
    roofObstacleProgressMin: z.number().min(0).max(1),
    roofObstacleProgressMax: z.number().min(0).max(1),
    parallelScrollScale: z.number().min(0).max(1),
    counterflowScrollScale: z.number().min(0).max(3),
    parallelRideDrainScale: z.number().min(1),
    durations: z.object({
      calm: z.number().positive(),
      buildUp: z.number().positive(),
      intense: z.number().positive(),
      peak: z.number().positive(),
      cooldown: z.number().positive(),
    }),
  }),
  camera: z.object({
    fov: z.number().positive(),
    fovMin: z.number().positive(),
    fovMax: z.number().positive(),
    positionY: z.number(),
    positionZ: z.number(),
    lookY: z.number(),
    positionYFollow: z.number().min(0).max(1),
    lookYFollow: z.number().min(0).max(1),
    carTurnBankScale: z.number().nonnegative(),
    horseTurnBankScale: z.number().nonnegative(),
    carTurnSpring: z.number().positive(),
    carTurnDamping: z.number().positive(),
    carTurnBodyYaw: z.number().nonnegative(),
    carTurnBodyRoll: z.number().nonnegative(),
    turnComboWindowSeconds: z.number().positive(),
    turnMomentumDecaySeconds: z.number().positive(),
    turnJellyScaleMax: z.number().min(1),
    turnBankScaleMax: z.number().min(1),
    turnPullbackZMax: z.number().nonnegative(),
    horsePresentationScale: z.number().min(0).max(1),
    horseFpsPresentationScale: z.number().min(0).max(1),
    horseFpsPullbackScale: z.number().min(0).max(1),
    dodgeDipY: z.number().nonnegative(),
    dodgePullbackZ: z.number().nonnegative(),
    dodgeLateralX: z.number().nonnegative(),
    dodgeMinSpeed: z.number().nonnegative(),
    dodgeInSeconds: z.number().nonnegative(),
    dodgeHoldSeconds: z.number().nonnegative(),
    dodgeOutSeconds: z.number().nonnegative(),
    dodgePresentationEnabled: z.boolean(),
    presentationClampX: z.number().nonnegative(),
    presentationClampY: z.number().nonnegative(),
    presentationClampZ: z.number().nonnegative(),
  }),
  hit: z.object({
    iframeSeconds: z.number().positive(),
    recoverySeconds: z.number().positive(),
    speedPenalty: z.number().min(0).max(1),
    zGrace: z.number().nonnegative(),
    zRearTrimRatio: z.number().min(0).max(0.5),
    heightGrace: z.number().nonnegative(),
  }),
  adrenaline: z.object({
    max: z.number().positive(),
    start: z.number().positive(),
    passiveDrainPerSecond: z.number().positive(),
    drainRampSeconds: z.number().nonnegative(),
    drainStartScale: z.number().min(0).max(1),
    idleLaneSeconds: z.number().nonnegative(),
    idleLaneDrainBonus: z.number().min(1),
    rocketDrainMultiplier: z.number().positive(),
    collisionDamage: z.number().positive(),
    collisionLowHpThreshold: z.number().nonnegative(),
    collisionLowHpMultiplier: z.number().min(1),
    damagedThresholdPercent: z.number().min(0).max(100),
    criticalThresholdPercent: z.number().min(0).max(100),
    criticalNitroGainMultiplier: z.number().min(1),
    gainSmash: z.number().nonnegative(),
    gainCoin: z.number().nonnegative(),
    gainCoinCarMultiplier: z.number().min(1),
    gainCoinHorseMultiplier: z.number().min(1),
    gainCoinRocketMultiplier: z.number().min(1),
    gainNearMiss: z.number().nonnegative(),
    gainHorseJumpClear: z.number().nonnegative(),
    gainHorseSlideClear: z.number().nonnegative(),
    gainNitroBurst: z.number().nonnegative(),
    nearMissMaxZ: z.number(),
  }),
  combo: z.object({
    threatDistance: z.number().positive(),
    multiplierStep: z.number().int().positive(),
    multiplierPerStep: z.number().int().positive(),
    chainWindowSeconds: z.number().positive(),
  }),
  pulse: z.object({
    decayPerSecond: z.number().positive(),
    strongBeatEnergyThreshold: z.number().nonnegative(),
    channels: z.object({
      background: z.number().nonnegative(),
      ambient: z.number().nonnegative(),
      objectsEmissive: z.number().nonnegative(),
      objectsScale: z.number().nonnegative(),
      coinsScale: z.number().nonnegative(),
      dashesEmissive: z.number().nonnegative(),
    }),
  }),
  turbo: z.object({
    energyThreshold: z.number().min(0).max(1),
    relativeRiseThreshold: z.number().min(0).max(1),
    historySeconds: z.number().positive(),
    percentile: z.number().min(0).max(1),
    beatSyncTimeoutSeconds: z.number().positive(),
    sustainSeconds: z.number().positive(),
    durationSeconds: z.number().positive(),
    cooldownSeconds: z.number().positive(),
    speedBoost: z.number().min(1),
    entrySeconds: z.number().nonnegative(),
    exitSeconds: z.number().nonnegative(),
    sceneLeadSeconds: z.number().positive(),
    sceneRows: z.number().int().positive(),
    earlyTrackSeconds: z.number().positive(),
    earlyTrackBeatSyncSeconds: z.number().positive(),
    earlyTrackEntrySeconds: z.number().nonnegative(),
  }).refine((value) => value.entrySeconds + value.exitSeconds < value.durationSeconds, {
    message: 'turbo entry and exit must leave a climax window',
  }),
  nitro: z.object({
    maxFill: z.number().positive(),
    gainPerCoin: z.number().nonnegative(),
    gainPerDodge: z.number().nonnegative(),
    gainPerChargeLaneSecond: z.number().nonnegative(),
    drainPerSecond: z.number().positive(),
    graceSeconds: z.number().nonnegative(),
    boostMax: z.number().nonnegative(),
    coinNitroMultiplier: z.number().nonnegative(),
    gainPerSmash: z.number().nonnegative(),
    gainPerNearMiss: z.number().nonnegative(),
    scoreMultiplier: z.number().min(1),
    camYOffset: z.number(),
    smashGraceSeconds: z.number().nonnegative(),
    readyCollisionBlastRadius: z.number().positive(),
    readyCollisionBlastStrength: z.number().min(1),
    warningSeconds: z.number().positive(),
    audioClearSeconds: z.number().positive(),
    audioShelfGainDb: z.number().nonnegative(),
    audioShelfFrequencyHz: z.number().positive(),
    audioGainBoost: z.number().nonnegative(),
    salvation: z.object({
      minChargePercent: z.number().min(0).max(100),
      baseChance: z.number().min(0).max(1),
      lateProgressStart: z.number().min(0).max(1),
      lateProgressBonus: z.number().min(0).max(1),
      lookaheadRows: z.number().int().positive(),
      minMultiLaneRows: z.number().int().nonnegative(),
      minTallAhead: z.number().int().nonnegative(),
      flashSeconds: z.number().positive(),
      smashStrengthMultiplier: z.number().positive(),
    }),
  }),
  postfx: z.object({
    blurMax: z.number().nonnegative(),
    blurInner: z.number().min(0).max(1),
    blurOuter: z.number().min(0).max(1),
    samples: z.number().int().positive(),
    blurSpread: z.number().nonnegative(),
    kickStrength: z.number().nonnegative(),
    shakeSpeed: z.number().nonnegative(),
    vigStrength: z.number().nonnegative(),
    vigInner: z.number().min(0).max(1),
    windMinSpeed: z.number().min(0).max(1),
    windFadeRange: z.number().positive(),
    windCount: z.number().int().nonnegative(),
    lineMaxLength: z.number().nonnegative(),
    lineMaxAlpha: z.number().nonnegative(),
    bankStrength: z.number().nonnegative(),
    shakeNitroBoost: z.number().nonnegative(),
    bankNitroBoost: z.number().nonnegative(),
    shakeSkillMomentumBoost: z.number().nonnegative(),
    greenSmashFovBoost: z.number().nonnegative(),
  }),
  player: z.object({
    width: z.number().positive(),
    height: z.number().positive(),
    depth: z.number().positive(),
  }),
  obstacle: z.object({
    width: z.number().positive(),
    depth: z.number().positive(),
    lowWidth: z.number().positive(),
    lowDepth: z.number().positive(),
    tallWidth: z.number().positive(),
    tallDepth: z.number().positive(),
    tallHeight: z.number().positive(),
    lowHeight: z.number().positive(),
    microHeight: z.number().positive(),
    microWidthScale: z.number().positive(),
    microDepthScale: z.number().positive(),
  }),
  destroy: z.object({
    gainPerMicroBreak: z.number().nonnegative(),
    gainPerMediumSmash: z.number().nonnegative(),
    gainPerDodge: z.number().nonnegative(),
    softHitSpeedPenalty: z.number().min(0).max(1),
    softHitPenaltySeconds: z.number().positive(),
    mediumHitSpeedPenalty: z.number().min(0).max(1),
    mediumHitPenaltySeconds: z.number().positive(),
    tallHitSpeedPenalty: z.number().min(0).max(1),
    microClusterProbability: z.number().min(0).max(1),
    microClusterSizeMin: z.number().int().positive(),
    microClusterSizeMax: z.number().int().positive(),
    microRowChance: z.number().min(0).max(1),
    mediumDensityScale: z.number().positive(),
    microChunkWeight: z.number().nonnegative(),
    obstacleChunkWeightBoost: z.number().nonnegative(),
    nitroTrafficMinLeadSeconds: z.number().nonnegative(),
    nitroTallProbabilityScale: z.number().positive(),
    nitroMicroSpawnScale: z.number().min(0).max(1),
    nitroMediumSpawnScale: z.number().min(0).max(1),
    nitroSmashRowChance: z.number().min(0).max(1),
    nitroMaxMediumPerLaneRows: z.number().int().positive(),
    nitroLateStartProgress: z.number().min(0).max(1),
    nitroLateChargeGainScale: z.number().min(0).max(1),
    nitroLateChallengeScale: z.number().min(0).max(1),
    nitroLateMicroSpawnScale: z.number().min(0).max(1),
    nitroLateMediumSpawnScale: z.number().min(0).max(1),
    laneCommitmentMaxSeconds: z.number().positive(),
    laneCommitmentNitroMaxSeconds: z.number().positive(),
    damageAudioMaxWet: z.number().min(0).max(1),
    damageAudioMinHz: z.number().positive(),
    damageAudioMaxGainReduction: z.number().min(0).max(1),
    damageAudioAttackSeconds: z.number().positive(),
    damageAudioReleaseSeconds: z.number().positive(),
    damageAudioDamagedStress: z.number().min(0).max(1),
    mediumKnockbackLateralSpeed: z.number().positive(),
    mediumKnockbackArcUpSpeed: z.number().positive(),
    mediumKnockbackGravity: z.number().positive(),
    mediumKnockbackBackwardSpeed: z.number(),
    mediumKnockbackGreenLateralSpeed: z.number().positive(),
    mediumKnockbackGreenArcUpSpeed: z.number().positive(),
    mediumKnockbackGreenGravity: z.number().positive(),
    mediumKnockbackGreenForwardSpeed: z.number(),
    mediumKnockbackYellowSpin: z.number().positive(),
    mediumKnockbackGreenSpin: z.number().positive(),
    mediumKnockbackGreenExplodeStrength: z.number().positive(),
    mediumKnockbackDurationSeconds: z.number().positive(),
    mediumKnockbackHitRadius: z.number().positive(),
    greenSmashSpeedBonus: z.number().nonnegative(),
    greenSmashSpeedDecaySeconds: z.number().positive(),
    earlyGreenSmashSpeedScale: z.number().min(1),
    earlyGreenSmashFullSeconds: z.number().nonnegative(),
    earlyGreenSmashFadeSeconds: z.number().positive(),
  }).refine((value) => value.microClusterSizeMax >= value.microClusterSizeMin, {
    message: 'microClusterSizeMax must be at least microClusterSizeMin',
  }),
  coin: z.object({
    radius: z.number().positive(),
    value: z.number().int().positive(),
    collectGrace: z.number().nonnegative(),
  }),
});

const directorIntentSchema = z.object({
  target: z.string(),
  value: z.union([z.number(), z.boolean()]),
  priority: z.number(),
  tag: z.string(),
});

const directorPhaseSchema = z.object({
  minDurationSeconds: z.number().nonnegative(),
  cooldownAfterExitSeconds: z.number().nonnegative(),
  center: z.number().min(0).max(1),
  intents: z.array(directorIntentSchema),
});

export const directorConfigSchema = z.object({
  scoring: z.object({
    wEnergy: z.number().nonnegative(),
    wStress: z.number().nonnegative(),
    wPhaseElapsed: z.number().nonnegative(),
    wBrightness: z.number().nonnegative(),
    cooldownPenalty: z.number().nonnegative(),
  }),
  music: z.object({
    speedEnergyInfluence: z.number().nonnegative(),
    vfxEnergyInfluence: z.number().nonnegative(),
    speedFloor: z.number().min(0).max(1),
    sectionEnergy: z.object({
      attackSeconds: z.number().positive(),
      releaseSeconds: z.number().positive(),
    }),
  }),
  phases: z.object({
    calm: directorPhaseSchema,
    buildUp: directorPhaseSchema,
    intense: directorPhaseSchema,
    peak: directorPhaseSchema,
    cooldown: directorPhaseSchema,
  }),
  constraints: z.object({
    maxSpeedDeltaPerSecond: z.number().nonnegative(),
    minSecondsBetweenMajorEvents: z.number().nonnegative(),
    minSecondsBetweenCameraChanges: z.number().nonnegative(),
    hysteresisUp: z.number().nonnegative(),
    hysteresisDown: z.number().nonnegative(),
  }),
  defaultIntents: z.array(directorIntentSchema),
});

export const levelgenConfigSchema = z.object({
  chunkLength: z.number().positive(),
  contentStartZ: z.number().nonnegative(),
  segmentsAhead: z.number().int().nonnegative(),
  segmentsBehind: z.number().int().nonnegative(),
  lanes: z.number().int().positive(),
  minGapZ: z.number().nonnegative(),
  segmentWeights: z.object({
    obstacle: z.number().nonnegative(),
    coins: z.number().nonnegative(),
    bonus: z.number().nonnegative(),
    empty: z.number().nonnegative(),
  }),
  densityRange: z.tuple([z.number(), z.number()]),
  baseDensity: z.number().min(0).max(1),
  musicDensityDeltaMax: z.number().nonnegative(),
  coinHeight: z.number().nonnegative(),
  coinRoutes: z.object({
    obstacleGuideProbability: z.number().min(0).max(1),
    riskChoiceProbability: z.number().min(0).max(1),
  }),
  fairness: z.object({
    referenceSpeed: z.number().positive(),
    speedSampleStep: z.number().min(0.5),
    laneSwitchSeconds: z.number().positive(),
    minDecisionSeconds: z.number().positive(),
    obstaclePaddingSeconds: z.number().nonnegative(),
    routeGuideShare: z.number().min(0).max(1),
    mandatoryRampGuideClusters: z.number().int().nonnegative(),
    freeRampGuideClusters: z.number().int().nonnegative(),
    microLeadMinGapZScale: z.number().min(0.5).max(4),
  }),
  carHazardSpacing: z.object({
    tallTallMinGapScale: z.number().min(1).max(4),
    mixedMinGapScale: z.number().min(1).max(4),
    lowLowMinGapScale: z.number().min(0.5).max(1),
    compactTallChains: z.boolean(),
  }),
  bonusLeadZ: z.number().positive(),
  bonusMinGapZ: z.number().nonnegative(),
  seedBehavior: z.enum(['session', 'fixed']),
  wallProbability: z.number().min(0).max(1),
  wallProbabilityNoNitro: z.number().min(0).max(1),
  wallCooldownSeconds: z.number().nonnegative(),
  nitroWallProbability: z.number().min(0).max(1),
  nitroActiveFullRowProbability: z.number().min(0).max(1),
  nitroReadyChallengeProbability: z.number().min(0).max(1),
  nitroReadyMandatoryProbability: z.number().min(0).max(1),
  nitroChallengeCooldownRows: z.number().int().nonnegative(),
  tallProbability: z.number().min(0).max(1),
  twoObstacleBias: z.number().min(0).max(1),
  shoulderPasserProbability: z.number().min(0).max(1),
  shoulderPasserSpeedMultiplier: z.number().positive(),
  minWallGapRows: z.number().int().nonnegative(),
  laneFlow: z.array(z.number()).length(4),
  multiLaneFlowFactor: z.number().min(0).max(1),
  counterflowPassabilityLingerSeconds: z.number().nonnegative(),
  counterflowSpawnLagScale: z.number().nonnegative(),
  nitroChargeLanes: z.array(z.number().int().nonnegative()).min(1),
  nitroCoinFrequencyMultiplier: z.number().min(0).max(1),
  rampProbability: z.number().min(0).max(1),
  earlyRampProbability: z.number().min(0).max(1),
  earlyRampRows: z.number().int().nonnegative(),
  rampMinGapRows: z.number().int().nonnegative(),
  redWallProbability: z.number().min(0).max(1),
  rampLeadRows: z.number().int().nonnegative(),
  longRunDifficulty: z.object({
    delaySeconds: z.number().nonnegative(),
    rampSeconds: z.number().positive(),
    maxDensityBonus: z.number().nonnegative(),
    maxMultiObstacleBiasBonus: z.number().nonnegative(),
    lateSongEaseStartProgress: z.number().min(0).max(1),
    lateSongEaseMaxReduction: z.number().min(0).max(1),
  }),
  earlyTallBias: z.number().min(0).max(0.5),
  trackEndObstacleStopSeconds: z.number().nonnegative(),
  earlyTraffic: z.object({
    rows: z.number().int().nonnegative(),
    densityBonus: z.number().nonnegative(),
    laneWeight: z.number().min(1),
    lanes: z.array(z.number().int().nonnegative()).min(1),
    forcedObstacleRows: z.number().int().nonnegative(),
    maxOpeningEmptyGapZ: z.number().positive(),
  }),
  riskZone: z.object({
    riskLanes: z.array(z.number().int().nonnegative()).min(1),
    obstacleWeight: z.number().min(0),
    coinWeight: z.number().min(0),
  }),
  car: z.object({
    phasesEnabled: z.boolean(),
    phaseMinChunks: z.number().int().positive(),
    phaseMaxChunks: z.number().int().positive(),
    phaseWeights: z.object({
      stream: z.number().nonnegative(),
      weave: z.number().nonnegative(),
      breather: z.number().nonnegative(),
      nitroTease: z.number().nonnegative(),
    }),
    waveMinChunks: z.number().int().positive(),
    waveMaxChunks: z.number().int().positive(),
    waveIntensityPeak: z.number().min(0).max(1),
    longRunWeaveWeightBonus: z.number().nonnegative(),
    longRunNitroTeaseWeightBonus: z.number().nonnegative(),
    longRunBreatherWeightPenalty: z.number().nonnegative(),
    streamLaneStickiness: z.number().min(0).max(1),
    streamDensityScale: z.number().min(0).max(2),
    weaveDensityScale: z.number().min(0).max(2),
    weaveMultiObstacleBiasBonus: z.number().min(0).max(1),
    breatherDensityScale: z.number().min(0).max(2),
    breatherObstacleWeightScale: z.number().min(0).max(1),
    nitroTeaseDensityScale: z.number().min(0).max(2),
    nitroTeaseReadyChallengeMultiplier: z.number().min(1).max(3),
    nitroTeaseCoinFrequencyMultiplier: z.number().min(0.5).max(2),
  }).refine((value) => value.phaseMaxChunks >= value.phaseMinChunks, {
    message: 'car phaseMaxChunks must be >= phaseMinChunks',
  }).refine((value) => value.waveMaxChunks >= value.waveMinChunks, {
    message: 'car waveMaxChunks must be >= waveMinChunks',
  }),
  horse: z.object({
    actionChunkProbability: z.number().min(0).max(1),
    slideGroupProbability: z.number().min(0).max(1),
    mandatoryActionProbability: z.number().min(0).max(1),
    jumpGroupMin: z.number().int().positive(),
    jumpGroupMax: z.number().int().positive(),
    slideGroupMin: z.number().int().positive(),
    slideGroupMax: z.number().int().positive(),
    longSlideGroupProbability: z.number().min(0).max(1),
    longSlideGroupMin: z.number().int().positive(),
    longSlideGroupMax: z.number().int().positive(),
    slideSpacingZ: z.number().positive(),
    jumpFollowupProbability: z.number().min(0).max(1),
    jumpFollowupSlideProbability: z.number().min(0).max(1),
    slideStartChunks: z.number().int().nonnegative(),
    restChunkProbability: z.number().min(0).max(1),
    slideToJumpMinGapZ: z.number().nonnegative(),
    highSpeedEaseStartMomentum: z.number().min(0).max(1),
    highSpeedActionMultiplier: z.number().min(0).max(1),
    highSpeedMandatoryMultiplier: z.number().min(0).max(1),
    highSpeedFollowupMultiplier: z.number().min(0).max(1),
    jumpCoinGroupProbability: z.number().min(0).max(1),
    jumpCoinHeight: z.number().positive(),
    groundCoinProbability: z.number().min(0).max(1),
    restCoinStride: z.number().int().positive(),
    coinMaxSameLaneStreak: z.number().int().positive(),
    coinWeaveStride: z.number().int().positive(),
    dodgeOnlyProbability: z.number().min(0).max(1),
    dodgeOnlyMaxGapChunks: z.number().int().positive(),
    dodgeBlockedMin: z.number().int().positive(),
    dodgeBlockedMax: z.number().int().positive(),
    maxSameActionStreak: z.number().int().positive(),
    slideFollowupDodgeProbability: z.number().min(0).max(1),
    convertibleShoulderPunishGapZ: z.number().positive(),
    slideCoinProbability: z.number().min(0).max(1),
    phasesEnabled: z.boolean(),
    phaseMinChunks: z.number().int().positive(),
    phaseMaxChunks: z.number().int().positive(),
    phaseWeights: z.object({
      corridor: z.number().nonnegative(),
      weave: z.number().nonnegative(),
      breather: z.number().nonnegative(),
      overdriveTease: z.number().nonnegative(),
    }),
    waveMinChunks: z.number().int().positive(),
    waveMaxChunks: z.number().int().positive(),
    waveIntensityPeak: z.number().min(0).max(1),
    longRunWeaveWeightBonus: z.number().nonnegative(),
    longRunOverdriveTeaseWeightBonus: z.number().nonnegative(),
    longRunBreatherWeightPenalty: z.number().nonnegative(),
    corridorActionScale: z.number().positive(),
    corridorDodgeProbabilityScale: z.number().nonnegative(),
    corridorDodgeLaneStickiness: z.number().min(0).max(1),
    weaveActionScale: z.number().positive(),
    weaveSlideProbabilityBonus: z.number().min(0).max(1),
    weaveFollowupScale: z.number().nonnegative(),
    weaveGroupSizeBonus: z.number().nonnegative(),
    breatherActionScale: z.number().positive(),
    breatherRestChunkScale: z.number().nonnegative(),
    breatherGroundCoinScale: z.number().nonnegative(),
    overdriveTeaseActionScale: z.number().positive(),
    overdriveTeaseMandatoryScale: z.number().nonnegative(),
    overdriveTeaseFollowupScale: z.number().nonnegative(),
    overdriveTeaseJumpCoinBonus: z.number().min(0).max(1),
    overdriveTeaseGroupSizeBonus: z.number().nonnegative(),
    frontierTownProbability: z.number().min(0).max(1),
    frontierTownIntroChunks: z.number().int().nonnegative(),
    frontierTownMinChunks: z.number().int().positive(),
    frontierTownMaxChunks: z.number().int().positive(),
    frontierTownCooldownChunks: z.number().int().nonnegative(),
  }).refine((value) => value.phaseMaxChunks >= value.phaseMinChunks, {
    message: 'horse phaseMaxChunks must be >= phaseMinChunks',
  }).refine((value) => value.waveMaxChunks >= value.waveMinChunks, {
    message: 'horse waveMaxChunks must be >= waveMinChunks',
  }).refine((value) => value.frontierTownMaxChunks >= value.frontierTownMinChunks, {
    message: 'horse frontierTownMaxChunks must be >= frontierTownMinChunks',
  }),
});

export const audioConfigSchema = z.object({
  latencyOffsetMs: z.number().nonnegative(),
  fftSize: z.number().int().positive(),
  blockSamples: z.number().int().positive(),
  energy: z.object({
    attackSeconds: z.number().positive(),
    releaseSeconds: z.number().positive(),
    minRiseSeconds: z.number().positive(),
    maxFallSeconds: z.number().positive(),
  }),
  brightness: z.object({
    attackSeconds: z.number().positive(),
    releaseSeconds: z.number().positive(),
    minRiseSeconds: z.number().positive(),
    maxFallSeconds: z.number().positive(),
  }),
  beat: z.object({
    thresholdK: z.number().positive(),
    minIntervalMs: z.number().nonnegative(),
    rollingWindow: z.number().int().positive(),
  }),
  silence: z.object({
    rmsThreshold: z.number().nonnegative(),
    minFrames: z.number().int().nonnegative(),
    debounceMs: z.number().nonnegative(),
    exitFactor: z.number().positive(),
  }),
  trackEndFadeSeconds: z.number().nonnegative(),
});

export const debugConfigSchema = z.object({
  prototypeMode: z.boolean(),
  recording: z.object({
    enabled: z.boolean(),
    autoExport: z.boolean(),
  }),
  timeline: z.object({
    zoomSecondsPerScreen: z.number().positive(),
  }),
  overlay: z.object({
    showFps: z.boolean(),
    showStates: z.boolean(),
    showIntents: z.boolean(),
  }),
});

export type GameConfig = z.infer<typeof gameConfigSchema>;
export const nitroSalvationConfigSchema = gameConfigSchema.shape.nitro.shape.salvation;
export type NitroSalvationConfig = z.infer<typeof nitroSalvationConfigSchema>;
export const adrenalineConfigSchema = gameConfigSchema.shape.adrenaline;
export type AdrenalineConfig = z.infer<typeof adrenalineConfigSchema>;
export type DirectorConfig = z.infer<typeof directorConfigSchema>;
export type LevelgenConfig = z.infer<typeof levelgenConfigSchema>;
export type AudioConfig = z.infer<typeof audioConfigSchema>;
export type DebugConfig = z.infer<typeof debugConfigSchema>;

export type ConfigKey = 'game' | 'director' | 'levelgen' | 'audio' | 'debug' | 'sfx';

export type Configs = {
  game: GameConfig;
  director: DirectorConfig;
  levelgen: LevelgenConfig;
  audio: AudioConfig;
  debug: DebugConfig;
  sfx: SfxConfig;
};

export const configSchemas: Record<ConfigKey, z.ZodType> = {
  game: gameConfigSchema,
  director: directorConfigSchema,
  levelgen: levelgenConfigSchema,
  audio: audioConfigSchema,
  debug: debugConfigSchema,
  sfx: sfxConfigSchema,
};
